
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  AUTH_HOST: auth-service
  AUTH_PORT: "8080"
  MANAGER_SERVICE_URL: "http://manager-service:8000"
  MANAGER_REPLICAS: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  SECRET_KEY: "change-me"
