apiVersion: batch/v1
kind: Job
metadata:
  name: reduce-job
spec:
  template:
    spec:
      restartPolicy: Never

      containers:
      - name: worker
        image: worker:
        imagePullPolicy: Never

        envFrom:
        - secretRef:
            name: postgres-secret
        - secretRef:
            name: minio-secret
        - configMapRef:
            name: postgres-config
        - configMapRef:
            name: minio-config

        command: ["python", "worker.py"]

        args:
          - "--task-json"
          - '{"task_id":"reduce-0","task_type":"reduce","input_bucket":"mapreduce","input_objects":["results/map-1-shuffle-part-0.jsonl"],"output_bucket":"mapreduce","output_object":"results/reduce-0.json","parameters":{"operation":"word_count","r_partitions":1,"reduce_partition_id":0,"partition_function":"sha256"}}'
