apiVersion: batch/v1
kind: Job
metadata:
  name: worker-job
spec:
  ttlSecondsAfterFinished: 30

  template:
    spec:
      restartPolicy: Never

      containers:
      - name: worker

        image: worker:latest
        imagePullPolicy: Never

        envFrom:
        - secretRef:
            name: postgres-secret
        - secretRef:
            name: minio-secret
        - configMapRef:
            name: postgres-config
        - configMapRef:
            name: minio-config

        command: ["python", "worker.py"]

        args:
          - "--task-json"
          - '{"task_id":"map-1","task_type":"map","input_bucket":"mapreduce","input_objects":["inputs/input.txt"],"output_bucket":"mapreduce","output_object":"results/map-1.json","parameters":{"operation":"word_count","input_format":"auto","case_sensitive":false,"r_partitions":1,"partition_function":"sha256"}}'
