apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  MINIO_ROOT_USER: admin
  MINIO_ROOT_PASSWORD: pass1234!

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
data:
  MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
  MINIO_SERVER_URL: "http://minio.svc.cluster.local:9000"
  MINIO_REGION_NAME: "local-dev"
  MINIO_PROMETHEUS_AUTH_TYPE: "public"

---
