apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
  MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
data:
  MINIO_BROWSER_REDIRECT_URL: "${MINIO_BROWSER_REDIRECT_URL}"
  MINIO_SERVER_URL: "${MINIO_SERVER_URL}"
  MINIO_REGION_NAME: "${MINIO_REGION_NAME}"
  MINIO_PROMETHEUS_AUTH_TYPE: "${MINIO_PROMETHEUS_AUTH_TYPE}"
  MINIO_SECURE: "${MINIO_SECURE}"

---
