apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "${POSTGRES_PORT}"
  PGDATA: "${PGDATA}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_JOBS_DB: "${POSTGRES_JOBS_DB}"
