apiVersion: batch/v1
kind: Job
metadata:
  name: worker-job
spec:
  ttlSecondsAfterFinished: 30

  template:
    spec:
      restartPolicy: Never

      containers:
      - name: worker

        image: ${WORKER_IMAGE}
        imagePullPolicy: ${WORKER_IMAGE_PULL_POLICY}

        envFrom:
        - secretRef:
            name: postgres-secret
        - secretRef:
            name: minio-secret
        - configMapRef:
            name: postgres-config
        - configMapRef:
            name: minio-config

        command: ["python", "worker.py"]

        args:
          - "--task-json"
          - '${MAP_TASK_JSON}'
