apiVersion: batch/v1
kind: Job
metadata:
  name: {{ worker_id }}
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: {{ image }}
          imagePullPolicy: Never
          command: ["python3", "worker.py"]
          args:
          {% for arg in args %}
          - {{ arg | tojson }}
          {% endfor %}
          envFrom:
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: minio-secret
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: minio-config
